export default [
  {
    id: 0,
    name: "Porshe 718 Cayman S",
    img: "/assets/data/1.png",
    price: "400",
    transmission: "Manual",
    details: "Coupe",
    capacity: "4",
  },
  {
    id: 1,
    name: "Porshe 718 Cayman S",
    img: "/assets/data/2.png",
    price: "400",
    transmission: "Manual",
    details: "Coupe",
    capacity: "4",
  },
  {
    id: 2,
    name: "Porshe 718 Cayman S",
    img: "/assets/data/3.png",
    price: "400",
    transmission: "Manual",
    details: "Coupe",
    capacity: "4",
  },
  {
    id: 3,
    name: "Porshe 718 Cayman S",
    img: "/assets/data/4.png",
    price: "400",
    transmission: "Manual",
    details: "Coupe",
    capacity: "4",
  },
  {
    id: 4,
    name: "Porshe 718 Cayman S",
    img: "/assets/data/5.png",
    price: "400",
    transmission: "Manual",
    details: "Coupe",
    capacity: "4",
  },
  {
    id: 5,
    name: "Porshe 718 Cayman S",
    img: "/assets/data/6.png",
    price: "400",
    transmission: "Manual",
    details: "Coupe",
    capacity: "4",
  },
  {
    id: 6,
    name: "Porshe 718 Cayman S",
    img: "/assets/data/7.png",
    price: "400",
    transmission: "Manual",
    details: "Coupe",
    capacity: "4",
  },
  {
    id: 7,
    name: "Porshe 718 Cayman S",
    img: "/assets/data/8.png",
    price: "400",
    transmission: "Manual",
    details: "Coupe",
    capacity: "4",
  },
  {
    id: 8,
    name: "Porshe 718 Cayman S",
    img: "/assets/data/9.png",
    price: "400",
    transmission: "Manual",
    details: "Coupe",
    capacity: "4",
  },
];
