export default  [
    {
      id: 0,
      name: "Porshe 718 Cayman S",
      img: "/puplic/assets/data/1.png",
      price: "80.00",
      transmission: "Manual",
      details: "Coupe",
    },
    {
      id: 1,
      name: "Porshe 718 Cayman S",
      img: "/puplic/assets/data/2.png",
      price: "400",
      transmission: "Manual",
      details: "Coupe",
    },
    {
      id: 2,
      name: "Porshe 718 Cayman S",
      img: "/puplic/assets/data/3.png",
      price: "400",
      transmission: "Manual",
      details: "Coupe",
    },
    {
      id: 3,
      name: "Porshe 718 Cayman S",
      img: "/puplic/assets/data/4.png",
      price: "400",
      transmission: "Manual",
      details: "Coupe",
    },
    {
      id: 4,
      name: "Porshe 718 Cayman S",
      img: "/puplic/assets/data/5.png",
      price: "400",
      transmission: "Manual",
      details: "Coupe",
    },
    {
      id: 5,
      name: "Porshe 718 Cayman S",
      img: "/puplic/assets/data/6.png",
      price: "400",
      transmission: "Manual",
      details: "Coupe",
    },
    {
      id: 6,
      name: "Porshe 718 Cayman S",
      img: "/puplic/assets/data/7.png",
      price: "400",
      transmission: "Manual",
      details: "Coupe",
    },
    {
      id: 7,
      name: "Porshe 718 Cayman S",
      img: "/puplic/assets/data/8.png",
      price: "400",
      transmission: "Manual",
      details: "Coupe",
    },
    {
      id: 8,
      name: "Porshe 718 Cayman S",
      img: "/puplic/assets/data/9.png",
      price: "400",
      transmission: "Manual",
      details: "Coupe",
    },
  ];
  